version: '3'

services:
  node:
    image: "node:12"
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules      
    ports:
      - "3000:3000"
    working_dir: /app
    command: sh -c "npm install && npm run generate && tail -f /dev/null"

volumes:
  node_modules:
