version: '3'

services:
  nginx:
    image: nginx
    env_file:
      - web.env
    restart: unless-stopped
    volumes:
      - ./gzip.conf:/etc/nginx/conf.d/gzip.conf
      - ./public:/usr/share/nginx/html:ro
    networks:
      - default
      - www

networks:
  www:
    external:
      name: www
