version: '3'

services:
  nginx:
    image: nginx
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./docker-nginx-gzip.conf:/etc/nginx/conf.d/gzip.conf
      - ./dist:/usr/share/nginx/html:ro
    networks:
      - default
      - www
      
networks:
  www:
    external:
      name: www
