name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: NPM Install
        run: npm ci

      - name: Fetch data
        run: npm run fetch

      - name: Remove temp files
        run: |
          rm ./static/data/orig/*

      - name: Generate
        env:
          TF_API_KEY: ${{ secrets.TF_API_KEY }}
        run: npm run generate

      - name: Git Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
