name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        
      - name: NPM Install
        run: npm ci
        
      - name: Generate
        run: npm run generate

      - name: Fetch data
        run: ./scripts/fetch.sh

      - name: Git Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
