name: Cron

on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2        
      
      - name: Checkout build
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: dist

      - name: NPM Install
        run: npm ci --only=production
          
      - name: Fetch data
        run: npm run fetch

      - name: Move files
        run: |
          cp ./static/data/*.geo.json ./dist/data/
          ls -lth ./dist/data/

      - name: Git Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: false
